spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/supportdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

life:
  app:
    jwt:
      secret: mySuperSecureJwtSecretKeyThatIsLongEnough123456
      expiration: 3600000

